"""
Data for THE NAME DIAL (weeks/week6/dial): everything needed to re-rank the lookalikes of any page while two
dials are turned, with no server and no model.

Write each page's TF-IDF vector as u = u_names + u_habit + u_other (the course page's definitions, unit length;
names and habit words as in scripts/week6_text.py). For any two pages the dot product splits into three
matrices that add up to the cosine:

    Pn[i][j] = u_names(i) . u_names(j)     Ph[i][j] likewise for habit words     Po[i][j] for every other word

Turn the names dial to w_n and the habit dial to w_h (each from 0 to 1) and multiply the matching part of every
vector by it, then renormalise. The cosine of pages i and j becomes

    ( w_n^2 Pn[i][j] + w_h^2 Ph[i][j] + Po[i][j] ) / ( norm(i) norm(j) ),   norm(i)^2 = w_n^2 Pn[i][i] + w_h^2 Ph[i][i] + Po[i][i]

so 1 and 1 is TF-IDF as the course defines it, 0 and 1 is TF-IDF with the names removed, 0 and 0 is names and habit
words removed. The three matrices are stored as integers, millionths, row by row.

  chars  name, Wikipedia url, lead image url, Louvain community (-1: outside the giant component), words, in-degree
  edges  every undirected link between two pages, as index pairs
  n h o  the three matrices, 303 x 303 each, in millionths

Writes data/week6_dial.js (window.DIAL). Deterministic.

Run:  python scripts/build_week6_dial.py
"""

import datetime
import json
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import week6_text as T                              # noqa: E402
from analyse import pretty                          # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = DATA / "week6_dial.js"
SCALE = 1_000_000


def load_images():
    path = DATA / "week2_images.js"
    if not path.exists():
        return {}
    s = path.read_text(encoding="utf-8")
    return json.loads(s[s.index("{"):s.rindex("}") + 1])


def main():
    m = T.build_model()
    ids, N = m.ids, m.N
    images = load_images()
    Un = m.Un
    parts = {
        "n": Un * m.isname,
        "h": Un * (m.ishabit & ~m.isname),
        "o": Un * ~(m.isname | m.ishabit),
    }
    mats = {k: np.rint((M @ M.T) * SCALE).astype(int) for k, M in parts.items()}
    chars = [{"id": n, "name": pretty(n), "url": "https://en.wikipedia.org/wiki/" + n,
              "img": images.get(n, {}).get("src"), "com": m.comm_of.get(n, -1), "tokens": int(m.length[i]),
              "kin": int(m.G.in_degree(n))} for i, n in enumerate(ids)]
    ix = m.ix
    edges = sorted({(min(ix[a], ix[b]), max(ix[a], ix[b])) for a, b in m.U.edges() if a != b})
    data = {"meta": {"built": datetime.date.today().isoformat(), "n_chars": N, "scale": SCALE, "n_edges": len(edges),
                     "communities": len(m.comms)},
            "chars": chars, "edges": edges,
            "n": mats["n"].ravel().tolist(), "h": mats["h"].ravel().tolist(), "o": mats["o"].ravel().tolist()}
    OUT.write_text("// Autogenerated by scripts/build_week6_dial.py - do not edit by hand.\n"
                   "window.DIAL = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size / 1024:.0f} kB): {N} pages, {len(edges)} links")
    diag = mats["n"].diagonal() + mats["h"].diagonal() + mats["o"].diagonal()
    print("diagonal sums to 1 (millionths): min", diag.min(), "max", diag.max())


if __name__ == "__main__":
    main()
