"""
Data for TABOO-IDF (weeks/week6/taboo): you type words, one at a time, to describe a secret Marvel character; after
every word the 303 pages are ranked by their cosine with your words, and you win when the target is first.

The machine that guesses is the course's lookalikes measure with the query being your word list: the cosine between
a binary vector of the words you typed and a page's unit-length TF-IDF vector (tf = count / words, idf = ln(303 / df)).
That cosine is the sum over your words of the page's weight for the word, divided by the square root of how many words
you typed, so the ranking only needs the sum. This file holds each page's weight for each word, as postings.

  words   every word on at least two pages (14,860 of the 25,254), in alphabetical order
  kind    0 other word, 1 name (scripts/week6_text.py's rule), 2 habit word (stopword, or on a third of the pages)
  df      pages containing the word
  ps      postings start offsets (len(words) + 1)
  pi, pv  postings: page index and that page's unit TF-IDF weight for the word, in hundred-thousandths
  chars   name, url, lead image url, words on the page, in-degree, and for pages with 800 words or more (the targets):
            oracle   the one non-name word that puts the page ahead of every other by the widest margin, with the margin
            oracle_any  the same with names allowed
            print    the twelve non-name, non-habit words with the largest weight on the page (its fingerprint)

An oracle that has read all 303 pages wins in one word, with or without names. The game is not about what the machine
can do; it is about what a person can guess about a page's vocabulary.

Writes data/week6_taboo.js (window.TABOO). Deterministic.

Run:  python scripts/build_week6_taboo.py
"""

import datetime
import json
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import week6_text as T                              # noqa: E402
from analyse import pretty                          # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = DATA / "week6_taboo.js"
SCALE = 100_000
MIN_DF = 2
MIN_TOKENS = 800
FINGERPRINT = 12


def load_images():
    path = DATA / "week2_images.js"
    if not path.exists():
        return {}
    s = path.read_text(encoding="utf-8")
    return json.loads(s[s.index("{"):s.rindex("}") + 1])


def oracle(Wm, t, allowed):
    """The single word (column of Wm, restricted to `allowed`) that makes page t beat every other page by the most."""
    others = np.delete(Wm, t, axis=0).max(axis=0)
    margin = np.where(allowed, Wm[t] - others, -9.0)
    j = int(np.argmax(margin))
    return j, float(margin[j])


def main():
    m = T.build_model()
    c, N = m.c, m.N
    images = load_images()
    sel = np.where(m.df >= MIN_DF)[0]                  # vocabulary is sorted, so this stays alphabetical
    Wm = m.Un[:, sel]
    names = np.array([c.vocab[i] for i in sel])
    kind = np.where(m.isname[sel], 1, np.where(m.ishabit[sel], 2, 0))

    ps, pi, pv = [0], [], []
    for k in range(len(sel)):
        pages = np.nonzero(Wm[:, k])[0]
        pi.extend(int(p) for p in pages)
        pv.extend(int(round(Wm[p, k] * SCALE)) for p in pages)
        ps.append(len(pi))

    plain = kind == 0
    chars = []
    for i, n in enumerate(m.ids):
        ch = {"id": n, "name": pretty(n), "url": "https://en.wikipedia.org/wiki/" + n, "img": images.get(n, {}).get("src"),
              "tokens": int(m.length[i]), "kin": int(m.G.in_degree(n))}
        if m.length[i] >= MIN_TOKENS:
            j, mg = oracle(Wm, i, ~(kind == 1))
            ja, mga = oracle(Wm, i, np.ones(len(sel), bool))
            fp = np.argsort(-np.where(plain, Wm[i], -1))[:FINGERPRINT]
            ch.update(oracle=[j, round(mg, 4)], oracle_any=[ja, round(mga, 4)], print=[int(x) for x in fp])
        chars.append(ch)
    targets = [i for i, ch in enumerate(chars) if "oracle" in ch]
    data = {"meta": {"built": datetime.date.today().isoformat(), "n_chars": N, "scale": SCALE, "min_df": MIN_DF,
                     "n_words": len(sel), "n_postings": len(pi), "n_targets": len(targets), "min_tokens": MIN_TOKENS,
                     "pages": N},
            "words": names.tolist(), "kind": kind.tolist(), "df": [int(x) for x in m.df[sel]],
            "ps": ps, "pi": pi, "pv": pv, "chars": chars}
    OUT.write_text("// Autogenerated by scripts/build_week6_taboo.py - do not edit by hand.\n"
                   "window.TABOO = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n", encoding="utf-8")
    kinds = np.bincount(kind)
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size / 1024:.0f} kB): {len(sel)} words "
          f"({kinds[0]} other, {kinds[1]} names, {kinds[2]} habit), {len(pi)} postings, {len(targets)} targets")
    ex = chars[m.ix["Storm_(Marvel_Comics)"]]
    print("Storm oracle (names banned):", names[ex["oracle"][0]], ex["oracle"][1], "| names allowed:", names[ex["oracle_any"][0]],
          "| fingerprint:", [names[x] for x in ex["print"][:6]])


if __name__ == "__main__":
    main()
