"""
Data for SECRET IDENTITY (weeks/week5/game): every character's page reduced to
a bag of words, plus the sentences the two other case types are built from.

  chars      one entry per character: the clue words under three weightings
             (raw counts, stopwords removed, distinctive), a truncated bag-of-words
             vector for the machine that plays against you, the five pages whose
             vectors point most in the same direction (the lookalike decoys), the
             Louvain community, in-degree, page length and the Wikipedia image URL
  impostor   real sentences from the pages and sentences generated by one trigram
             model per community, both passed through the same detokenizer
  redacted   concordance lines with one content word blanked out, the answer, and
             three decoys, two of them from NLTK's similar(): words that occupy the
             same left-and-right contexts as the answer somewhere in the corpus

Clue words never include the character's own names (title, real name, and the
subject of the page's first sentence). "Distinctive" ranks by count x ln(303 / df),
which is next week's TF-IDF a week early; the post says so.

Writes data/week5_secret.js (window.SECRET). Run after scripts/analyse_week5.py
is not required; both compute the same communities from the same seed.

Run:  python scripts/build_week5_data.py
"""

import collections
import datetime
import json
import math
import pathlib
import random
import re
import sys

import networkx as nx
import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import week5_text as W                              # noqa: E402
from analyse import load_graph, pretty              # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = DATA / "week5_secret.js"
N_CLUES, N_VEC, N_LOOK = 25, 200, 5
N_REAL, N_REDACTED = 300, 160
SEED = 55


def load_images():
    path = DATA / "week2_images.js"
    if not path.exists():
        return {}
    s = path.read_text(encoding="utf-8")
    return json.loads(s[s.index("{"):s.rindex("}") + 1])


def main():
    rng = random.Random(SEED)
    pages = W.load_pages()
    docs = W.load_tokens(pages)
    G = load_graph()
    ids = sorted(docs)
    index = {n: i for i, n in enumerate(ids)}
    images = load_images()

    # ---- communities, the same call as the analysis
    UG = G.to_undirected()
    giant = UG.subgraph(max(nx.connected_components(UG), key=len)).copy()
    q, comms, seed = W.louvain_best(giant)
    com = {n: i for i, c in enumerate(comms) for n in c}
    cnames = [" / ".join(pretty(n) for n in sorted(c, key=lambda n: -G.degree(n))[:2]) for c in comms]

    # ---- bags of words
    all_counts = {n: collections.Counter(W.words(docs[n])) for n in ids}
    nostop_counts = {n: collections.Counter(W.words(docs[n], stop=True)) for n in ids}
    df = collections.Counter()
    for n in ids:
        df.update(all_counts[n].keys())
    N = len(ids)
    vocab, vid = [], {}

    def wid(w):
        if w not in vid:
            vid[w] = len(vocab)
            vocab.append(w)
        return vid[w]

    chars = []
    vecs = {}
    for n in ids:
        mask = W.mask_tokens(G, n, docs[n])
        raw = [(w, c) for w, c in all_counts[n].most_common() if w not in mask][:N_CLUES]
        nostop = [(w, c) for w, c in nostop_counts[n].most_common() if w not in mask][:N_CLUES]
        scored = sorted(((c * math.log(N / df[w]), w, c) for w, c in nostop_counts[n].items() if c >= 2 and w not in mask),
                        reverse=True)
        distinct = [(w, c) for _, w, c in scored[:N_CLUES]]
        # the machine's vector: stopword-removed counts, L2-normalised, top terms kept
        norm = math.sqrt(sum(c * c for c in nostop_counts[n].values())) or 1.0
        vec = sorted(((c / norm, w) for w, c in nostop_counts[n].items()), reverse=True)[:N_VEC]
        vecs[n] = {w: round(x, 4) for x, w in vec}
        chars.append({
            "id": n, "name": pretty(n), "url": "https://en.wikipedia.org/wiki/" + n,
            "img": images.get(n, {}).get("src"), "com": com.get(n, -1), "kin": G.in_degree(n), "kout": G.out_degree(n),
            "tokens": sum(all_counts[n].values()), "types": len(all_counts[n]),
            "mask": sorted(mask),
            "clues": {"raw": [[wid(w), c] for w, c in raw], "nostop": [[wid(w), c] for w, c in nostop],
                      "distinct": [[wid(w), c] for w, c in distinct]},
            "vec": [[wid(w), x] for w, x in vecs[n].items()],
        })
    # lookalikes from the full stopword-removed vectors (cosine)
    from sklearn.feature_extraction.text import CountVectorizer
    from sklearn.preprocessing import normalize
    X = normalize(CountVectorizer(token_pattern=r"\S+").fit_transform([" ".join(W.words(docs[n], stop=True)) for n in ids]))
    S = np.asarray((X @ X.T).todense())
    np.fill_diagonal(S, -1)
    for i, ch in enumerate(chars):
        ch["look"] = [int(j) for j in np.argsort(-S[i])[:N_LOOK]]
    dfl = [df[w] for w in vocab]

    # ---- impostor: real sentences and trigram fakes, same detokenizer
    clean = {n: W.clean_sentences(docs[n], lo=10, hi=28) for n in ids}
    guard = [s for v in clean.values() for s in v]
    stream_guard = [W.raw_tokens(docs[n]) for n in ids]        # whole pages, so no fake copies any run of 9
    real = []
    pool = [(n, s) for n in ids for s in clean[n] if len(clean[n]) >= 4]
    rng.shuffle(pool)
    per_page = collections.Counter()
    for n, s in pool:
        if per_page[n] >= 2:
            continue
        per_page[n] += 1
        real.append({"t": W.detok(s), "w": s, "real": 1, "src": index[n], "com": com.get(n, -1)})
        if len(real) >= N_REAL:
            break
    # generated sentences, matched to the real ones length for length so nothing
    # as cheap as "the short one is the fake" works
    fakes = []
    total = sum(len(c) for c in comms)
    quota = collections.Counter(len(it["w"]) for it in real)
    candidates = []
    for ci, c in enumerate(comms):
        m = W.TrigramModel([s for n in c for s in clean.get(n, [])])
        m.add_guard(guard)
        m.add_guard(stream_guard)
        want = round(N_REAL * len(c) / total)
        for s in m.generate(random.Random(SEED + ci), want * 5, lo=10, hi=28):
            candidates.append((ci, s))
    rng.shuffle(candidates)
    used_per_com = collections.Counter()
    share = {ci: N_REAL * len(c) / total for ci, c in enumerate(comms)}
    for ci, s in sorted(candidates, key=lambda x: used_per_com[x[0]]):
        if quota[len(s)] <= 0 or used_per_com[ci] >= share[ci] + 2:
            continue
        quota[len(s)] -= 1
        used_per_com[ci] += 1
        fakes.append({"t": W.detok(s), "w": s, "real": 0, "src": -1, "com": ci})
    # anything the quotas could not fill (rare lengths), fill from the leftovers
    leftovers = [(ci, s) for ci, s in candidates if not any(f["w"] == s for f in fakes)]
    for ci, s in leftovers:
        if len(fakes) >= len(real):
            break
        fakes.append({"t": W.detok(s), "w": s, "real": 0, "src": -1, "com": ci})
    impostor = real + fakes
    rng.shuffle(impostor)

    # ---- redacted: concordance lines with a blank, decoys from similar()
    from nltk.text import ContextIndex
    stream = [t[W.LOWER] for n in ids for t in docs[n]["tokens"] if not t[W.IS_SPACE]]
    ctx = ContextIndex(stream, filter=lambda w: w.isalpha())
    corpus_count = collections.Counter(w for n in ids for w in W.words(docs[n]))
    case_upper = collections.Counter()
    case_all = collections.Counter()
    for n in ids:
        for t in docs[n]["tokens"]:
            if t[W.IS_ALPHA]:
                case_all[t[W.LOWER]] += 1
                case_upper[t[W.LOWER]] += t[W.TEXT][0].isupper()
    targets = [w for w, c in corpus_count.items() if 60 <= c <= 1500 and len(w) >= 4 and w not in W.STOPWORDS
               and case_upper[w] / case_all[w] < 0.15]
    rng.shuffle(targets)
    freq_pool = [w for w in targets]
    redacted = []
    for w in targets:
        if len(redacted) >= N_REDACTED:
            break
        cands = [(n, s) for n in ids for s in clean[n] if sum(1 for x in s if x.lower() == w) == 1
                 and not any(x.lower() != w and w in x.lower() for x in s)]
        if not cands:
            continue
        n, s = rng.choice(cands)
        pos = next(i for i, x in enumerate(s) if x.lower() == w)
        blanked = list(s)
        blanked[pos] = "▮▮▮▮"
        similar = [x for x in ctx.similar_words(w, 30) if x.isalpha() and x not in W.STOPWORDS and len(x) >= 4
                   and x != w and corpus_count[x] >= 30 and x not in {y.lower() for y in s}]
        sim = similar[:2]
        others = [x for x in freq_pool if x != w and x not in sim and x not in {y.lower() for y in s}
                  and 0.5 <= corpus_count[x] / corpus_count[w] <= 2.0]
        rng.shuffle(others)
        decoys = sim + others[:3 - len(sim)]
        if len(decoys) < 3:
            continue
        options = [w] + decoys
        flags = [0] + [1] * len(sim) + [0] * (3 - len(sim))
        order = list(range(4))
        rng.shuffle(order)
        redacted.append({"t": W.detok(blanked), "a": s[pos], "o": [options[k] for k in order],
                         "sim": [flags[k] for k in order], "src": index[n], "n": corpus_count[w], "df": df[w], "w": s})

    payload = {
        "meta": {"built": datetime.date.today().isoformat(), "n_chars": len(chars), "n_impostor": len(impostor),
                 "n_real": len(real), "n_fake": len(fakes), "n_redacted": len(redacted), "louvain_q": round(q, 3),
                 "louvain_seed": seed, "clues_per_weighting": N_CLUES, "vec_terms": N_VEC,
                 "weightings": {"raw": "raw counts, every word", "nostop": "NLTK stopwords removed",
                                "distinct": "count x ln(303 / pages containing the word)"}},
        "vocab": vocab, "df": dfl,
        "communities": {"names": cnames, "sizes": [len(c) for c in comms]},
        "chars": chars, "impostor": impostor, "redacted": redacted,
    }
    OUT.write_text("// Autogenerated by scripts/build_week5_data.py - do not edit by hand.\n"
                   "// SECRET IDENTITY: bags of words for 303 characters, real and generated sentences, concordance blanks.\n"
                   "window.SECRET = " + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n",
                   encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size / 1024:.0f} kB): {len(chars)} characters, "
          f"{len(real)} real + {len(fakes)} generated sentences, {len(redacted)} blanks, vocabulary {len(vocab)}")
    print("communities:", list(zip(cnames, [len(c) for c in comms])))
    print("sample clues (distinct):", [(vocab[v], c) for v, c in chars[index["Spider-Man"]]["clues"]["distinct"][:8]])
    print("sample fake:", fakes[0]["t"])
    print("sample blank:", redacted[0]["t"], redacted[0]["o"], redacted[0]["a"])


if __name__ == "__main__":
    main()
