"""
Data for the ORIGIN STORY explorable (weeks/week2/grow).

The explorable replays the frozen Marvel network in order of first appearance,
so it needs each hero's debut year next to the graph the game already ships
(data/marvel_week1.js, from scripts/build_graph.py). This writes the years, read
from the week-2 crawl, as a .js file for the same reason the graph is one: the
page then also runs straight from file:// without a server.

Also writes data/week2_combined.js: the heroes-plus-villains network from the
crawl (nodes with side and year, directed edges by index), so the explorable
can replay the universe with its villains in it.

Run:  python scripts/build_week2_data.py      (after scripts/crawl_week2.py)
"""

import csv
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "week2_years.js"
OUT2 = ROOT / "data" / "week2_combined.js"


def read_tsv(path):
    with open(path, encoding="utf-8") as f:
        lines = [line for line in f if not line.startswith("#")]
    return list(csv.DictReader(lines, delimiter="\t"))


def main():
    roster = {r["node_id"] for r in read_tsv(ROOT / "week1_nodes.tsv")}
    years = {}
    for r in read_tsv(ROOT / "data" / "week2_nodes.tsv"):
        if r["node_id"] in roster and r["debut_year"]:
            years[r["node_id"]] = int(r["debut_year"])
    missing = sorted(roster - set(years))

    nodes = read_tsv(ROOT / "data" / "week2_nodes.tsv")
    index = {r["node_id"]: i for i, r in enumerate(nodes)}
    edges = [[index[r["source"]], index[r["target"]]] for r in read_tsv(ROOT / "data" / "week2_edges.tsv")]
    payload = {
        "nodes": [{"id": r["node_id"], "name": r["name"], "side": r["side"],
                   "year": int(r["debut_year"]) if r["debut_year"] else None, "url": r["url"]} for r in nodes],
        "edges": edges,
    }
    OUT2.write_text(
        "// Autogenerated by scripts/build_week2_data.py from data/week2_nodes.tsv and data/week2_edges.tsv.\n"
        f"// Heroes + villains, {len(nodes)} nodes and {len(edges)} directed edges, crawled from live Wikipedia.\n"
        "window.MARVEL_COMBINED = " + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8")
    print(f"wrote {OUT2.relative_to(ROOT)}: {len(nodes)} nodes, {len(edges)} edges")
    OUT.write_text(
        "// Autogenerated by scripts/build_week2_data.py from data/week2_nodes.tsv - do not edit by hand.\n"
        "// Year of first appearance per character, read from the Wikipedia infobox. "
        f"{len(years)} of {len(roster)} heroes have one.\n"
        "window.MARVEL_YEARS = " + json.dumps(years, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(years)} years, {len(missing)} missing: {missing}")


if __name__ == "__main__":
    main()
