"""
Portraits for SYMPOSIUM.

Asks the Wikipedia API for the page image of every philosopher in the
week-4 snapshot (the infobox portrait: a painting, an engraving, a bust, a
photograph for the 19th century) and writes the thumbnail URLs to
data/week4_images.js. Only URLs are stored; the game loads the pictures from
Wikipedia at view time and credits the file, exactly as ORIGIN STORY does
for the Marvel characters. Philosophers without a page image get a drawn
placeholder in the game.

Run:  python scripts/fetch_week4_images.py        (about a minute, 29 API calls)
"""

import csv
import json
import pathlib
import time
import urllib.parse
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
NODES = ROOT / "week4_philosophers_nodes.tsv"
OUT = ROOT / "data" / "week4_images.js"
API = "https://en.wikipedia.org/w/api.php"
UA = ("SocialGraphs2026-Week4/1.0 (DTU 02805 student project; "
      "https://github.com/Oddvar112/Social-Graphs-and-Interactions)")
SIZE = 200


def api(params):
    params = dict(params, format="json", formatversion="2")
    req = urllib.request.Request(API + "?" + urllib.parse.urlencode(params), headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r)


def read_tsv(path):
    with open(path, encoding="utf-8") as f:
        lines = [line for line in f if not line.startswith("#")]
    return list(csv.DictReader(lines, delimiter="\t", quoting=csv.QUOTE_NONE))


def main():
    ids = [r["node_id"] for r in read_tsv(NODES)]
    by_title = {i.replace("_", " "): i for i in ids}
    images = {}
    titles = list(by_title)
    for i in range(0, len(titles), 50):
        chunk = titles[i:i + 50]
        d = api({"action": "query", "prop": "pageimages", "pilicense": "any", "pithumbsize": str(SIZE),
                 "titles": "|".join(chunk)})
        q = d.get("query", {})
        norm = {n["to"]: n["from"] for n in q.get("normalized", [])}
        for page in q.get("pages", []):
            title = norm.get(page["title"], page["title"])
            node_id = by_title.get(title)
            if node_id and "thumbnail" in page:
                t = page["thumbnail"]
                images[node_id] = {"src": t["source"].split("?")[0], "w": t["width"], "h": t["height"],
                                   "file": page.get("pageimage", "")}
        time.sleep(0.25)
        print(f"   {min(i + 50, len(titles))}/{len(titles)}")
    OUT.write_text(
        "// Autogenerated by scripts/fetch_week4_images.py - do not edit by hand.\n"
        f"// Page image of each philosopher's Wikipedia article, {SIZE}px thumbnails, URLs only. "
        f"{len(images)} of {len(ids)} philosophers have one. Loaded from Wikipedia at view time and credited.\n"
        "window.PHILOSOPHER_IMAGES = " + json.dumps(images, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8")
    missing = sorted(set(ids) - set(images))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(images)} portraits, {len(missing)} without, e.g. {missing[:8]}")


if __name__ == "__main__":
    main()
