"""
Lead images for the ORIGIN STORY pop-ups.

Asks the Wikipedia API for each character's page image (heroes and villains) (the infobox picture,
which for a Marvel character is almost always a comic panel or cover) and
writes the thumbnail URLs to data/week2_images.js. Only URLs are stored: the
pictures are non-free comic art that Wikipedia hosts under fair use, so the
explorable loads them from Wikipedia at view time, credits the file, and shows
a drawn placeholder when a character has none or the image has moved.

pilicense=any is what makes this work at all; the default, free images only,
returns nothing for this category.

Run:  python scripts/fetch_images.py
"""

import csv
import json
import pathlib
import time
import urllib.parse
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "week2_images.js"
API = "https://en.wikipedia.org/w/api.php"
UA = ("SocialGraphs2026-Week2/1.0 (DTU 02805 student project; "
      "https://github.com/Oddvar112/Social-Graphs-and-Interactions)")
SIZE = 320


def api(params):
    params = dict(params, format="json", formatversion="2")
    req = urllib.request.Request(API + "?" + urllib.parse.urlencode(params), headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r)


def read_tsv(path):
    with open(path, encoding="utf-8") as f:
        lines = [line for line in f if not line.startswith("#")]
    return list(csv.DictReader(lines, delimiter="\t"))


def main():
    ids = [r["node_id"] for r in read_tsv(ROOT / "data" / "week2_nodes.tsv")]     # heroes and villains
    by_title = {i.replace("_", " "): i for i in ids}
    images = {}
    titles = list(by_title)
    for i in range(0, len(titles), 50):
        chunk = titles[i:i + 50]
        d = api({"action": "query", "prop": "pageimages", "pilicense": "any", "pithumbsize": str(SIZE),
                 "titles": "|".join(chunk)})
        q = d.get("query", {})
        norm = {n["to"]: n["from"] for n in q.get("normalized", [])}
        for page in q.get("pages", []):
            title = norm.get(page["title"], page["title"])
            node_id = by_title.get(title)
            if node_id and "thumbnail" in page:
                t = page["thumbnail"]
                images[node_id] = {"src": t["source"].split("?")[0], "w": t["width"], "h": t["height"],
                                   "file": page.get("pageimage", "")}
        time.sleep(0.25)
        print(f"   {min(i + 50, len(titles))}/{len(titles)}")
    OUT.write_text(
        "// Autogenerated by scripts/fetch_images.py - do not edit by hand.\n"
        f"// Lead image of each character's Wikipedia article (heroes and villains), {SIZE}px thumbnails, URLs only. "
        f"{len(images)} of {len(ids)} characters have one. Non-free comic art, credited on the page.\n"
        "window.MARVEL_IMAGES = " + json.dumps(images, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8")
    missing = sorted(set(ids) - set(images))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(images)} images, {len(missing)} without: {missing[:10]}...")


if __name__ == "__main__":
    main()
